# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ow02drK-OwdGrMUhfMaOKEv0hBmwdV0H
"""

import pandas as pd

import seaborn as sns

df=sns.load_dataset("iris")

type(df)

df.head()

df.columns

df.index

names =["anuj", "Ravi","Mohit" ]
ages=[26,34,21]

d={
    "name":names,
    "age" :ages
}

d

pd.DataFrame(d)

import numpy as np

data=np.random.randint(10,20,(10,5))

data

marks=pd.DataFrame(data,columns=["p","c","m","e","ss"],index=["Basha","Abdul","Haja","Hameed","Jameel","Rahman","Faraj","Kader","Asfan","Ahamed"])

marks["bio"]=0

marks

df.values

df.describe()

df.T

df.index

df.columns

marks.sort_index(axis=1)

marks.sort_index(axis=0)

marks.sort_values(["e"])

marks.iloc[:5,1:]

marks.iloc[0:10:2]

marks.iloc[[0,2,4,6]]

